name: radioanaunia
description: App per Radio Anaunia, radio locale che trasmette da Cles in provincia di Trento.

publish_to: "none"

version: 5.0.0+4

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_series: ^0.1.2
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  volume_controller: ^2.0.7
  marquee: ^2.2.3
  auto_size_text: ^3.0.0
  http: ^1.0.0
  palette_generator: ^0.3.3+2
  image_fade: ^0.6.2
  provider: ^6.0.5
  just_audio: ^0.9.34
  audio_video_progress_bar: ^2.0.1
  rxdart: ^0.27.7
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  image_path_ios: assets/icon/icon_ios.png
  adaptive_icon_foreground: assets/icon/adaptive_foreground.png
  adaptive_icon_background: "#FFFFFF"

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/splash_screen.png
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    color_dark: "#1C1C1C"